### PR TITLE
feat(Struct): added evolve

### PR DESCRIPTION
**Pull request by jessekelly881**
Migrated struct/evolve from fp-ts with minor changes.

### CODE REVIEW

**Comment by jessekelly881** [comment]
What kinds of problems? I generally find it pretty useful.

**Comment by gcanti** [comment]
https://github.com/gcanti/fp-ts/issues?q=evolve

**Comment by jessekelly881** [comment]
It seems like the most commonly sited issue(which is still an issue after updating the fn a bit) is that passing a function directly as a prop is broken at the type level. I.e. 

```js
    const fn = <T>(x: T) => x

    const res1 = pipe(
      { a: "a", b: 1, c: true, d: "extra" },
      S.evolve({
        a: (s) => s.length,
        b: (b) => b > 0,
        c: fn
      })
    )
```

The returned type of c is unknown. I will see if I can fix this.

**Comment by jessekelly881** [comment]
Going down the rabbit hole a bit, it looks this is a limit with typescript. It's not possible to get the return type of a generic fn which is what we need for this to work. Ramda itself has the same issue when passed generic functions.

**Comment by jessekelly881** [comment]
Given the limit, do you think we should leave it out entirely or maybe just add a warning? It feels like a shame not to include it because of a limit in ts. It's generally a pretty useful function.

**Comment by gcanti** [comment]
> It's generally a pretty useful function

I'm not able to judge, I think I'll leave the decision to the community

**Pull request merged**
